constellation:
    operator: starlink
    number_of_shells: 1
    shell1:
        name: shell1
        # orbits: 9
        orbits: 72
        sat_per_orbit: 8
        altitude: 1500
        elevation_angle: 30
        inclination: 53
    topology:
        association_criteria_GSL: BASED_ON_DISTANCE_ONLY_MININET
        ISL: grid
        association_criteria_ISL: DOTD
    routing:
        algorithm: static_latency
        ip_range: 12.0.0.0
        interDomain_routing: 0
        border_gateway: gs26
        other_constellation_ip_range: 11.0.0.0

ground_stations:
    gs_file: /home/farzad/repos/SimLEO_MConstellations/mobility/gs.txt  #../mobility/ground_stations_experiments.txt

simulation:
    start_time: 2024,10,03,04,05,32
    length: 1
    step: 30
    debug: 1

application:
    type: ping
    source: gs0
    destination: gs1
    duration: 30
    congestion_control: cubic
    result_out: /home/farzad/repos/SimLEO_MConstellations/output/analysis/metrics/GS0_GS1_ping.txt
    background_traffic: no
    tcpdump: no

resiliency:
  type: takedown
  affected_satellites: ["sat198", "sat454"]
  s_timestamps: ["2022,12,30,14,0,50", "2022,12,30,14,0,50"]
  e_timestamps: ["2022,12,30,14,1,20", "2022,12,30,14,1,20"]

data_n_results:
    connectivity_matrix: /home/farzad/repos/SimLEO_MConstellations/output/connectivity_matrix/starlink/
    routing: /home/farzad/repos/SimLEO_MConstellations/output/routing/starlink/
    simulation_results: /home/farzad/repos/SimLEO_MConstellations/output/general/starlink
